/**
 * Unit tests for the wp-theme-control Node port's pure helpers
 * (bin/wp-theme-control/lib/*).
 */

import path from 'path';
import { fileURLToPath } from 'url';
import {
	parseCommonArgs,
	assertSafeSlug,
	sha256File,
	BakeError,
} from '../../bin/wp-theme-control/lib/context.js';
import {
	buildPatternFile,
	runtimePatternSlug,
	runtimePatternDescription,
} from '../../bin/wp-theme-control/lib/patterns.js';
import { validateFontFile } from '../../bin/wp-theme-control/lib/fonts.js';
import {
	buildFontsOverlay,
	buildStylesOverlay,
	iterFontFaces,
	rewriteFontSources,
} from '../../bin/wp-theme-control/lib/overlay.js';

const __dirname = path.dirname( fileURLToPath( import.meta.url ) );

describe( 'parseCommonArgs', () => {
	test( 'routes WP-CLI global args and toggles independently', () => {
		const parsed = parseCommonArgs( [
			'--path=/srv/wp',
			'--dry-run',
			'--url=http://site.test',
			'--user=admin',
			'manifest.tsv',
			'--force',
		] );

		expect( parsed.wpGlobalArgs ).toEqual( [
			'--path=/srv/wp',
			'--url=http://site.test',
			'--user=admin',
		] );
		expect( parsed.dryRun ).toBe( true );
		expect( parsed.force ).toBe( true );
		expect( parsed.clean ).toBe( false );
		expect( parsed.rest ).toEqual( [ 'manifest.tsv' ] );
	} );

	test( 'rejects an empty --state-dir', () => {
		expect( () => parseCommonArgs( [ '--state-dir=' ] ) ).toThrow(
			BakeError
		);
	} );

	test( 'defaults the state dir to .wp-theme-control in the cwd', () => {
		expect( parseCommonArgs( [] ).stateDir ).toContain(
			'.wp-theme-control'
		);
	} );
} );

describe( 'assertSafeSlug (upstream charset guard)', () => {
	test.each( [ 'welcome-banner', 'inter', 'hidden-template-part-header.1' ] )(
		'accepts %s',
		( slug ) => {
			expect( () => assertSafeSlug( slug ) ).not.toThrow();
		}
	);

	test.each( [ '', '../etc', '.hidden', 'two words', 'UPPER', 'a/b' ] )(
		'refuses %s',
		( slug ) => {
			expect( () => assertSafeSlug( slug ) ).toThrow( BakeError );
		}
	);
} );

describe( 'buildPatternFile (upstream wpctl_build_pattern_file)', () => {
	test( 'builds a namespaced pattern with all headers', () => {
		const content = buildPatternFile( {
			title: 'Welcome Banner',
			slug: 'test-theme/welcome-banner',
			categories: 'featured, call-to-action',
			inserter: 'yes',
			body: '<!-- wp:paragraph --><p>Hi</p><!-- /wp:paragraph -->',
		} );

		expect( content ).toMatch( /^<\?php\n\/\*\*\n/ );
		expect( content ).toContain( ' * Title: Welcome Banner' );
		expect( content ).toContain( ' * Slug: test-theme/welcome-banner' );
		expect( content ).toContain(
			' * Categories: featured, call-to-action'
		);
		expect( content ).toContain( ' * Inserter: yes' );
		expect( content.trimEnd().endsWith( '<!-- /wp:paragraph -->' ) ).toBe(
			true
		);
	} );

	test( 'omits empty categories/description and neutralizes docblock breaks', () => {
		const content = buildPatternFile( {
			title: 'Bad */ Title\nSecond',
			slug: 'test-theme/bad',
			inserter: 'no',
			body: '<!-- wp:paragraph /-->',
		} );

		expect( content ).not.toContain( ' * Categories:' );
		expect( content ).not.toContain( ' * Description:' );
		expect( content ).toContain( ' * Title: Bad * / Title Second' );
	} );
} );

describe( 'runtime pattern naming (upstream helpers)', () => {
	test( 'maps template types to hidden- pattern slugs', () => {
		expect( runtimePatternSlug( 'wp_template', 'home' ) ).toBe(
			'hidden-template-home'
		);
		expect( runtimePatternSlug( 'wp_template_part', 'header' ) ).toBe(
			'hidden-template-part-header'
		);
		expect( () => runtimePatternSlug( 'wp_block', 'x' ) ).toThrow(
			BakeError
		);
	} );

	test( 'descriptions mark managed files', () => {
		expect( runtimePatternDescription( 'wp_template', 'home' ) ).toBe(
			'Generated by wp-theme-control from wp_template home.'
		);
	} );
} );

describe( 'validateFontFile (magic-byte signatures)', () => {
	test( 'accepts woff2/woff/otf/ttf signatures', () => {
		expect(
			validateFontFile( Buffer.from( 'wOF2data', 'latin1' ), 'woff2' )
		).toBe( true );
		expect(
			validateFontFile( Buffer.from( 'wOFFdata', 'latin1' ), 'woff' )
		).toBe( true );
		expect(
			validateFontFile( Buffer.from( 'OTTOdata', 'latin1' ), 'otf' )
		).toBe( true );
		expect(
			validateFontFile(
				Buffer.from( '\x00\x01\x00\x00', 'latin1' ),
				'ttf'
			)
		).toBe( true );
	} );

	test( 'rejects mismatched signatures and unknown extensions', () => {
		expect(
			validateFontFile( Buffer.from( 'wOFFdata', 'latin1' ), 'woff2' )
		).toBe( false );
		expect(
			validateFontFile( Buffer.from( 'wOF2data', 'latin1' ), 'exe' )
		).toBe( false );
	} );

	test( 'validates the EOT signature at offset 8', () => {
		const eot = Buffer.alloc( 12 );
		eot.writeUInt32BE( 0x00000100, 8 );
		expect( validateFontFile( eot, 'eot' ) ).toBe( true );
	} );
} );

describe( 'iterFontFaces + rewriteFontSources', () => {
	const families = [
		{
			slug: 'inter',
			name: 'Inter',
			fontFamily: 'Inter, sans-serif',
			preview: 'ignored',
			fontFace: [
				{
					fontFamily: 'Inter',
					fontWeight: '300',
					fontStyle: 'normal',
					src: 'http://example.test/uploads/fonts/inter-300.woff2',
					preview: 'ignored',
				},
				{
					fontFamily: 'Inter',
					fontWeight: '700',
					src: [ 'file:./local.woff2' ],
				},
			],
		},
	];

	test( 'iterates every face source as flat rows', () => {
		const rows = iterFontFaces( families );

		expect( rows ).toHaveLength( 2 );
		expect( rows[ 0 ] ).toMatchObject( {
			familySlug: 'inter',
			fontFamily: 'Inter',
			fontWeight: '300',
			sourceIndex: 0,
			src: 'http://example.test/uploads/fonts/inter-300.woff2',
		} );
		expect( rows[ 1 ] ).toMatchObject( {
			fontWeight: '700',
			sourceIndex: 0,
			src: 'file:./local.woff2',
		} );
	} );

	test( 'rewrites sources through the staged map and strips preview', () => {
		const rewritten = rewriteFontSources( families, {
			'http://example.test/uploads/fonts/inter-300.woff2':
				'file:./assets/fonts/inter/inter-300-normal.woff2',
		} );

		expect( rewritten[ 0 ].preview ).toBeUndefined();
		expect( rewritten[ 0 ].fontFace[ 0 ].src[ 0 ] ).toBe(
			'file:./assets/fonts/inter/inter-300-normal.woff2'
		);
		expect( rewritten[ 0 ].fontFace[ 0 ].preview ).toBeUndefined();
		expect( rewritten[ 0 ].fontFace[ 1 ].src[ 0 ] ).toBe(
			'file:./local.woff2'
		);
	} );
} );

describe( 'overlay assembly (SPEC-016 §2)', () => {
	test( 'fonts overlay normalizes a fresh file with empty settings/styles', () => {
		const overlay = buildFontsOverlay( null, {
			themeFamilies: [ { slug: 'inter' } ],
			customFamilies: [ { slug: 'inter', fontFace: [] } ],
			recordId: '301',
			capturedAt: '2026-09-08T12:00:00Z',
		} );

		expect( overlay.settings ).toEqual( {} );
		expect( overlay.styles ).toEqual( {} );
		expect( overlay.fonts ).toEqual( {
			themeFamilies: [ { slug: 'inter' } ],
			customFamilies: [ { slug: 'inter', fontFace: [] } ],
		} );
		expect( overlay.globalStylesPostId ).toBe( 301 );
		expect( overlay.$comment ).toContain( 'Baked by rig:bake' );
	} );

	test( 'fonts overlay preserves an existing styles capture', () => {
		const existing = buildStylesOverlay( null, {
			userData: { settings: { color: { custom: false } }, styles: {} },
			recordId: '301',
			capturedAt: '2026-09-08T12:00:00Z',
		} );
		const merged = buildFontsOverlay( existing, {
			themeFamilies: [],
			customFamilies: [ { slug: 'inter' } ],
			recordId: '301',
			capturedAt: '2026-09-08T12:01:00Z',
		} );

		expect( merged.settings ).toEqual( { color: { custom: false } } );
		expect( merged.fonts.customFamilies ).toEqual( [ { slug: 'inter' } ] );
	} );

	test( 'styles overlay preserves the fonts block and overwrites settings/styles', () => {
		const existing = buildFontsOverlay( null, {
			themeFamilies: [ { slug: 'theme-serif' } ],
			customFamilies: [ { slug: 'inter' } ],
			recordId: '301',
			capturedAt: '2026-09-08T12:00:00Z',
		} );

		const overlay = buildStylesOverlay( existing, {
			userData: {
				settings: { color: { custom: false, duotone: [] } },
				styles: { color: { text: '#111111' } },
				isGlobalStylesUserThemeJSON: true,
				version: 3,
			},
			recordId: '301',
			capturedAt: '2026-09-08T12:02:00Z',
		} );

		expect( overlay.settings ).toEqual( {
			color: { custom: false, duotone: [] },
		} );
		expect( overlay.styles ).toEqual( { color: { text: '#111111' } } );
		expect( overlay.fonts.themeFamilies ).toEqual( [
			{ slug: 'theme-serif' },
		] );
		// Guard keys from the captured data never enter the overlay.
		expect( overlay.isGlobalStylesUserThemeJSON ).toBeUndefined();
		expect( overlay.version ).toBeUndefined();
	} );

	test( 'sha256File matches the CLI shasum output', () => {
		const file = path.join( __dirname, 'fixtures', 'core-blocks' );
		expect(
			typeof sha256File( path.join( file, 'paragraph', 'block.json' ) )
		).toBe( 'string' );
	} );

	test( 'font manifest rows are tab-separated 5-column TSV (hashable)', () => {
		const file = path.join( __dirname, 'fixtures', 'core-blocks' );
		const hash = sha256File( path.join( file, 'paragraph', 'block.json' ) );
		expect( hash ).toMatch( /^[0-9a-f]{64}$/ );
	} );
} );
